// TaskyJ.Interface.React/ClientApp/src/components/NavMenu.tsx
import * as React from 'react';
import { Collapse, Container, Navbar, NavbarBrand, NavbarToggler, NavItem, NavLink } from 'reactstrap';
import { Link } from 'react-router-dom';
import './NavMenu.css';

export default class NavMenu extends React.PureComponent<{}, { isOpen: boolean }> {
    public state = {
        isOpen: false
    };

    public render() {
        return (
            <header>
                <Navbar className="navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" light>
                    <Container>
                        <NavbarBrand tag={Link} to="/">TaskyJ.Interface.React</NavbarBrand>
                        <NavbarToggler onClick={this.toggle} className="mr-2"/>
                        <Collapse className="d-sm-inline-flex flex-sm-row-reverse" isOpen={this.state.isOpen} navbar>
                            <ul className="navbar-nav flex-grow">
                                <NavItem>
                                    <NavLink tag={Link} className="text-dark" to="/">Home</NavLink>
                                </NavItem>
                                <NavItem>
                                    <NavLink tag={Link} className="text-dark" to="/counter">Counter</NavLink>
                                </NavItem>
                                <NavItem>
                                    <NavLink tag={Link} className="text-dark" to="/fetch-data">Fetch data</NavLink>
                                </NavItem>
                            </ul>
                        </Collapse>
                    </Container>
                </Navbar>
            </header>
        );
    }

    private toggle = () => {
        this.setState({
            isOpen: !this.state.isOpen
        });
    }
}

// TaskyJ.Interface.Angular/ClientApp/src/app/nav-menu/nav-menu.component.ts
import { AuthenticationService } from '../services/authentication.service';
import { Component } from '@angular/core';
import { Router, ParamMap, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-nav-menu',
  templateUrl: './nav-menu.component.html',
  styleUrls: ['./nav-menu.component.css']
})
export class NavMenuComponent {
  isExpanded = false;
  public user: string;
  public showdeleted: boolean = true;

  constructor(
    private authenticationService: AuthenticationService,
    private route: ActivatedRoute
  ) {
      if (this.authenticationService.currentUserValue)
        this.user = this.authenticationService.currentUserValue.userName;
    this.route.queryParams.subscribe((params: ParamMap) => {
      this.showdeleted = (params['showdeleted'] === 'true');
    });
  }

  collapse() {
    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }
}

<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
      <a class="navbar-brand" [routerLink]="['/']">TaskyJ.Interface.Angular</a> {{ user }}
      <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow">
          <li class="nav-item">
            <a class="nav-link text-dark" href="#" onclick="window.location.reload()">Refresh ↺</a>
          </li>
          <li class="nav-item"
              [routerLinkActive]="['link-active']"
              [routerLinkActiveOptions]="{ exact: true }">
            <a class="nav-link text-dark" [routerLink]="['/task/new']">Add new +</a>
          </li>
          <li *ngIf="!showdeleted" class="nav-item" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/tasklist']" [queryParams]="{ showdeleted: true }">Show deleted Ѻ</a>
          </li>
          <li *ngIf="showdeleted" class="nav-item" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/tasklist']" [queryParams]="{ showdeleted: false }">Hide deleted Ѻ</a>
          </li>
          <li class="nav-item" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/users']">Manage users 👤</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
